### PR TITLE
Handle venues that have no associated papers.

### LINKED ISSUE #126: Building proceedings without papers
Some workshops have no papers but still want proceedings with invited talks abstracts and schedule.
However, when `papers.yml` is empty, they get [this error](https://github.com/emnlp-2022/SSLL/actions/runs/3491907520/jobs/5845088039):
```
Traceback (most recent call last):
  File "aclpub2/bin/generate", line 40, in <module>
    generate_proceedings(args.path, args.overwrite, args.outdir)
  File "/home/runner/work/SSLL/SSLL/aclpub2/aclpub2/generate.py", line 45, in generate_proceedings
    ) = load_configs(root)
  File "/home/runner/work/SSLL/SSLL/aclpub2/aclpub2/config.py", line 25, in load_configs
    for paper in papers:
TypeError: 'NoneType' object is not iterable
```

### PR DESCRIPTION
**Pull request by zhzhang**
Closes #126 and #127.

### CODE REVIEW

**Comment by zhzhang** [comment]
In this change, the output will be marked as "front_matter", but is meant to be used as the full proceedings for particular venues that do not have associated papers. @mjpost is there any issue with that output format?

**Comment by mjpost** [comment]
Can you post an example of what is different?

If a volume has only frontmatter (paper ID 0), that's fine. In that case the full volume (which has no paper ID) might be identical to the frontmatter—or either volume could be omitted.

**Comment by zhzhang** [comment]
@mjpost, I amended the PR, the output in the case of no papers will be a `proceedings.pdf`, and the inputs folder copied in, but no `watermarked_pdfs` folder.
The `proceedings.pdf` will stop at the venue schedule.

**Comment by mjpost** [comment]
That sounds sensible, though I think the venue schedule is typically part of the front matter. However, it doesn't matter whether this is provided as a single paper with ID 0, or as part of the complete book.

**Comment by zhzhang** [comment]
@mjpost please approve the PR if it looks good!

**Comment by zhzhang** [comment]
pulling in @crux82 for a review, please take a look when you get the change!

**Comment by crux82** [comment]
@zhzhang @mjpost  I checked and it seems to work. 

I removed the papers.yml and program.yml files and the proceedings were generated without papers.
The code seems ok! (Great work as always)

I only have a (significant) doubt: what if I want to generate proceedings without papers but with a program? 
Can I add papers in the program.yml file without having them in the papers.yml ones? 
(Sorry after these months I do not remember). 
I think that people will not have watermarked  PDF files but a program

**Review by ryancotterell — APPROVED** [review]

**Comment by zhzhang** [comment]
re @crux82 's concern, added a `frontmatter` flag that stops the compilation at the front matter, for venues where papers are to be included in the schedule, but not in the overall proceedings.

**Pull request merged**
